version: '3'
services:
  bookingService:
    container_name: bookingService
    image: booking_service:local
    build: .
    ports:
      - "15005:15005"
    environment:
      PORT: 15005
      MESSAGE_QUEUE_URI: amqp://guest:guest@rabbitmq
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:32768/postgres